### ISSUE TITLE
error Couldn't find package "@svgr/core@^4.3.3" required by "react-native-svg-transformer" on the "npm" registry.

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [kristerkari/react-native-svg-transformer#103]
getting this error when try to install this library in react native 0.63.2

error Couldn't find package "@svgr/core@^4.3.3" required by "react-native-svg-transformer" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@svgr/plugin-svgo@^4.3.1" required by "react-native-svg-transformer" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:36528:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:317:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by ManigandanRaamanathan** [comment]
@kristerkari

**Comment by kristerkari** [comment]
I tried installing the library and it worked, so might just be some temporary problem in the npm registry. Could you please try again?

**Comment by ManigandanRaamanathan** [comment]
Yep. It is fixed now
